/**
 * DEVELOPMENT SAMPLE DATA
 *
 * Used only when the FastAPI backend is unreachable in a non-production build
 * (see lib/api/client.ts). Values were carried over from the previous frontend's
 * local development fixtures. Every screen that renders this data shows a
 * visible "Development sample data" notice. It is never used in production.
 */
import type {
  CandidateDuplicatePair,
  FilterOptions,
  NationalOverviewResponse,
  WorkRecord,
} from "@/lib/types";

export const SAMPLE_OVERVIEW: NationalOverviewResponse = {
  summary: {
    total_allocated_funds: 83336700000,
    total_sanctioned_amount: 41688600000,
    total_disbursed_amount: 18873200000,
    total_works: 79068,
    completed_works: 11791,
    high_risk_works: 29,
    critical_works: 0,
  },
  risk_distribution: { LOW: 74117, MEDIUM: 4922, HIGH: 29, CRITICAL: 0 },
  top_states: [
    { state: "UTTAR PRADESH", total_works: 15019, total_sanctioned: 7630592770, total_disbursed: 4210000000, high_risk_works: 17 },
    { state: "BIHAR", total_works: 4545, total_sanctioned: 3392002636, total_disbursed: 1980000000, high_risk_works: 6 },
    { state: "MANIPUR", total_works: 77, total_sanctioned: 204700909, total_disbursed: 120000000, high_risk_works: 2 },
    { state: "MAHARASHTRA", total_works: 2420, total_sanctioned: 2324916470, total_disbursed: 1450000000, high_risk_works: 2 },
    { state: "ANDHRA PRADESH", total_works: 2998, total_sanctioned: 1967300701, total_disbursed: 1120000000, high_risk_works: 1 },
    { state: "WEST BENGAL", total_works: 4804, total_sanctioned: 3277889557, total_disbursed: 1890000000, high_risk_works: 1 },
    { state: "ASSAM", total_works: 1619, total_sanctioned: 1022844554, total_disbursed: 610000000, high_risk_works: 0 },
  ],
  category_distribution: [
    { work_category: "Roads & Infrastructure", total_works: 28450, total_sanctioned: 15400000000, high_risk_works: 12 },
    { work_category: "Education & Schools", total_works: 18200, total_sanctioned: 9800000000, high_risk_works: 7 },
    { work_category: "Water & Sanitation", total_works: 14300, total_sanctioned: 7200000000, high_risk_works: 5 },
    { work_category: "Health & Community", total_works: 10100, total_sanctioned: 5600000000, high_risk_works: 3 },
    { work_category: "Irrigation & Agri", total_works: 8018, total_sanctioned: 4100000000, high_risk_works: 2 },
  ],
};

export const SAMPLE_WORKS: WorkRecord[] = [
  {
    work_id: "WS/MP863/2026-2027/295003",
    work_category: "Roads & Infrastructure",
    State: "KARNATAKA",
    Constituency: "BANGALORE CENTRAL",
    mp_name: "P. C. Mohan",
    description: "Construction of CC Road in Ward 112 Bengaluru Central Constituency",
    sanction_amount: 1000000,
    effective_expenditure: 850000,
    peer_category_median_amount: 350000,
    amount_to_peer_ratio: 2.86,
    has_evidence_image: false,
    top_vendor: "M CUBE INFRATECH PRIVATE LIMITED",
    top_vendor_share: 0.85,
    financial_risk_score: 72,
    financial_risk_level: "HIGH",
    financial_explanation: "Sanction amount is 2.86x the peer median for similar CC road works in Karnataka.",
    vendor_risk_score: 94,
    vendor_risk_level: "CRITICAL",
    vendor_risk_explanation: "Vendor accounts for 85% of constituency sanctions; concentration indicator requires review.",
    duplicate_risk_score: 88,
    compliance_risk_score: 80,
    compliance_risk_level: "CRITICAL",
    compliance_explanation: "No completion evidence image recorded prior to 85% fund release.",
    composite_risk_score: 83.5,
    overall_risk_level: "HIGH",
    explainable_audit_summary: "Multiple indicators: single-vendor concentration (85%), high peer cost ratio, missing evidence image.",
    recommended_reviewer_action: "Review subsequent payment releases pending physical inspection and vendor contract review.",
  },
  {
    work_id: "WS/MP863/2026-2027/295007",
    work_category: "Roads & Infrastructure",
    State: "KARNATAKA",
    Constituency: "BANGALORE CENTRAL",
    mp_name: "P. C. Mohan",
    description: "Construction of Cement Concrete Road Work in Ward 112",
    sanction_amount: 1000000,
    effective_expenditure: 850000,
    peer_category_median_amount: 350000,
    amount_to_peer_ratio: 2.86,
    has_evidence_image: false,
    top_vendor: "M CUBE INFRATECH PRIVATE LIMITED",
    top_vendor_share: 0.85,
    financial_risk_score: 72,
    financial_risk_level: "HIGH",
    financial_explanation: "Identical sanction amount to WS/MP863/2026-2027/295003 with a high peer ratio.",
    vendor_risk_score: 94,
    vendor_risk_level: "CRITICAL",
    vendor_risk_explanation: "Vendor holds a dominant share of constituency sanctions.",
    duplicate_risk_score: 92.5,
    compliance_risk_score: 80,
    compliance_risk_level: "CRITICAL",
    compliance_explanation: "No completion evidence image recorded.",
    composite_risk_score: 84.6,
    overall_risk_level: "HIGH",
    explainable_audit_summary: "High text similarity (92.5%) with WS/MP863/2026-2027/295003 in the same ward. Potential duplicate candidate.",
    recommended_reviewer_action: "Verify site location against WS/MP863/2026-2027/295003.",
  },
  {
    work_id: "WS/MP18200/2025-2026/189492",
    work_category: "Education & Schools",
    State: "UTTAR PRADESH",
    Constituency: "AMETHI",
    mp_name: "Kishori Lal Sharma",
    description: "Construction of Additional Classrooms in Inter College Amethi",
    sanction_amount: 1746000,
    effective_expenditure: 1400000,
    peer_category_median_amount: 520000,
    amount_to_peer_ratio: 3.35,
    has_evidence_image: true,
    top_vendor: "AADI AND RUDRANSH CONSTRUCTION COMPANY",
    top_vendor_share: 1,
    financial_risk_score: 82.5,
    financial_risk_level: "CRITICAL",
    financial_explanation: "Sanction amount is 3.35x the peer median for classroom construction in Uttar Pradesh.",
    vendor_risk_score: 75,
    vendor_risk_level: "HIGH",
    vendor_risk_explanation: "Single contractor for all school infrastructure sanctions in the constituency.",
    duplicate_risk_score: 45,
    compliance_risk_score: 30,
    compliance_risk_level: "LOW",
    compliance_explanation: "Completion evidence image recorded.",
    composite_risk_score: 78.2,
    overall_risk_level: "HIGH",
    explainable_audit_summary: "Upper-tail cost outlier (3.35x peer median) and single-vendor concentration.",
    recommended_reviewer_action: "Request bill of quantities and rate verification.",
  },
  {
    work_id: "WS/MP517/2025-2026/206050",
    work_category: "Water & Sanitation",
    State: "UTTAR PRADESH",
    Constituency: "FATEHPUR SIKRI",
    mp_name: "Rajkumar Chahar",
    description: "Installation of Submersible Deep Borewell Water Supply Scheme",
    sanction_amount: 3739000,
    effective_expenditure: 2900000,
    peer_category_median_amount: 1100000,
    amount_to_peer_ratio: 3.4,
    has_evidence_image: false,
    top_vendor: "ONN INFRATECH",
    top_vendor_share: 1,
    financial_risk_score: 84,
    financial_risk_level: "CRITICAL",
    financial_explanation: "Sanction amount is 3.40x the regional median for water supply schemes.",
    vendor_risk_score: 74,
    vendor_risk_level: "HIGH",
    vendor_risk_explanation: "Single contractor for all sanctioned water works in the block.",
    duplicate_risk_score: 50,
    compliance_risk_score: 75,
    compliance_risk_level: "HIGH",
    compliance_explanation: "Completion certificate and evidence image not recorded.",
    composite_risk_score: 77.8,
    overall_risk_level: "HIGH",
    explainable_audit_summary: "Cost outlier (3.40x peer median) and 100% contractor concentration.",
    recommended_reviewer_action: "Field inspection of borewell installation site recommended.",
  },
  {
    work_id: "WS/MP517/2025-2026/206052",
    work_category: "Water & Sanitation",
    State: "UTTAR PRADESH",
    Constituency: "FATEHPUR SIKRI",
    mp_name: "Rajkumar Chahar",
    description: "Installation of Deep Borewell Piped Water Scheme Fatehpur Sikri Block",
    sanction_amount: 3739000,
    effective_expenditure: 2900000,
    peer_category_median_amount: 1100000,
    amount_to_peer_ratio: 3.4,
    has_evidence_image: false,
    top_vendor: "ONN INFRATECH",
    top_vendor_share: 1,
    financial_risk_score: 84,
    financial_risk_level: "CRITICAL",
    financial_explanation: "Identical sanction amount and specification to WS/MP517/2025-2026/206050.",
    vendor_risk_score: 74,
    vendor_risk_level: "HIGH",
    vendor_risk_explanation: "Single contractor for all sanctioned water works in the block.",
    duplicate_risk_score: 89,
    compliance_risk_score: 75,
    compliance_risk_level: "HIGH",
    compliance_explanation: "Evidence image not recorded.",
    composite_risk_score: 80.5,
    overall_risk_level: "HIGH",
    explainable_audit_summary: "High similarity (89%) duplicate candidate with matching sanction amount.",
    recommended_reviewer_action: "Cross-verify location against WS/MP517/2025-2026/206050.",
  },
  {
    work_id: "WS/MP18226/2025-2026/187959",
    work_category: "Health & Community",
    State: "UTTAR PRADESH",
    Constituency: "KHERI",
    mp_name: "Utkarsh Verma",
    description: "Construction of Community Hall & Cultural Centre",
    sanction_amount: 2354000,
    effective_expenditure: 1900000,
    peer_category_median_amount: 850000,
    amount_to_peer_ratio: 2.77,
    has_evidence_image: false,
    top_vendor: "SHIV KUMAR THEKEDAR",
    top_vendor_share: 1,
    financial_risk_score: 68,
    financial_risk_level: "HIGH",
    financial_explanation: "Cost ratio of 2.77x relative to the peer category median.",
    vendor_risk_score: 70,
    vendor_risk_level: "HIGH",
    vendor_risk_explanation: "Single contractor for community hall construction orders.",
    duplicate_risk_score: 30,
    compliance_risk_score: 70,
    compliance_risk_level: "HIGH",
    compliance_explanation: "No evidence image recorded prior to payment release.",
    composite_risk_score: 69.3,
    overall_risk_level: "HIGH",
    explainable_audit_summary: "Elevated cost ratio and missing evidence image.",
    recommended_reviewer_action: "Site inspection report from the executing agency recommended.",
  },
];

export const SAMPLE_DUPLICATE_PAIRS: CandidateDuplicatePair[] = [
  {
    work_id_1: "WS/MP863/2026-2027/295003",
    work_id_2: "WS/MP863/2026-2027/295007",
    state: "KARNATAKA",
    constituency: "BANGALORE CENTRAL",
    similarity_score: 92.5,
    sanction_amount_1: 1000000,
    sanction_amount_2: 1000000,
    description_1: "Construction of CC Road in Ward 112 Bengaluru Central Constituency",
    description_2: "Construction of Cement Concrete Road Work in Ward 112",
    sanction_date_1: "2026-03-12",
    sanction_date_2: "2026-04-05",
    duplicate_risk_level: "CRITICAL",
    nlp_explanation: "High TF-IDF cosine similarity (92.5%) and identical sanction amount within Ward 112.",
  },
  {
    work_id_1: "WS/MP517/2025-2026/206050",
    work_id_2: "WS/MP517/2025-2026/206052",
    state: "UTTAR PRADESH",
    constituency: "FATEHPUR SIKRI",
    similarity_score: 89,
    sanction_amount_1: 3739000,
    sanction_amount_2: 3739000,
    description_1: "Installation of Submersible Deep Borewell Water Supply Scheme",
    description_2: "Installation of Deep Borewell Piped Water Scheme Fatehpur Sikri Block",
    sanction_date_1: "2025-11-20",
    sanction_date_2: "2025-12-14",
    duplicate_risk_level: "HIGH",
    nlp_explanation: "Matching sanction amount and high text overlap in water supply scheme titles.",
  },
];

export const SAMPLE_FILTERS: FilterOptions = {
  states: ["UTTAR PRADESH", "BIHAR", "KARNATAKA", "MAHARASHTRA", "MANIPUR", "WEST BENGAL", "ANDHRA PRADESH"],
  categories: ["Roads & Infrastructure", "Education & Schools", "Water & Sanitation", "Health & Community", "Irrigation & Agri"],
  severities: ["CRITICAL", "HIGH", "MEDIUM", "LOW"],
};
